version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        env_file:
            - .env
        extra_hosts:
            - host.docker.internal:host-gateway
        ports:
            - 49000:3000
        depends_on:
            - redis
            - db
    redis:
        image: 'redis:7.2.5'
