version: '3'

services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 49000:3000
